// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StopPolyDataMessage` (type_id: STP_POLYDATA).
// Header-only (no body content).

#ifndef __igtlStopPolyDataMessage_h
#define __igtlStopPolyDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StopPolyDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StopPolyDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StopPolyDataMessage);

 protected:
    StopPolyDataMessage()  { m_SendMessageType = "STP_POLYDATA"; }
    ~StopPolyDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStopPolyDataMessage_h
