// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::PolyDataMessage` (type_id: POLYDATA).

#ifndef __igtlPolyDataMessage_h
#define __igtlPolyDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT PolyDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::PolyDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::PolyDataMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    PolyDataMessage()  { m_SendMessageType = "POLYDATA"; }
    ~PolyDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlPolyDataMessage_h
