// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::PointMessage` (type_id: POINT).

#ifndef __igtlPointMessage_h
#define __igtlPointMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT PointMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::PointMessage, igtl::MessageBase);
    igtlNewMacro(igtl::PointMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    PointMessage()  { m_SendMessageType = "POINT"; }
    ~PointMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlPointMessage_h
