// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StartTrackingDataMessage` (type_id: STT_TDATA).
// Header-only (no body content).

#ifndef __igtlStartTrackingDataMessage_h
#define __igtlStartTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StartTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StartTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StartTrackingDataMessage);

 protected:
    StartTrackingDataMessage()  { m_SendMessageType = "STT_TDATA"; }
    ~StartTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStartTrackingDataMessage_h
