// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::RTSPolyDataMessage` (type_id: RTS_POLYDATA).
// Header-only (no body content).

#ifndef __igtlRTSPolyDataMessage_h
#define __igtlRTSPolyDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT RTSPolyDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::RTSPolyDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::RTSPolyDataMessage);

 protected:
    RTSPolyDataMessage()  { m_SendMessageType = "RTS_POLYDATA"; }
    ~RTSPolyDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlRTSPolyDataMessage_h
