// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::TrajectoryMessage` (type_id: TRAJ).

#ifndef __igtlTrajectoryMessage_h
#define __igtlTrajectoryMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT TrajectoryMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::TrajectoryMessage, igtl::MessageBase);
    igtlNewMacro(igtl::TrajectoryMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    TrajectoryMessage()  { m_SendMessageType = "TRAJ"; }
    ~TrajectoryMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlTrajectoryMessage_h
