// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::SensorMessage` (type_id: SENSOR).

#ifndef __igtlSensorMessage_h
#define __igtlSensorMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT SensorMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::SensorMessage, igtl::MessageBase);
    igtlNewMacro(igtl::SensorMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    SensorMessage()  { m_SendMessageType = "SENSOR"; }
    ~SensorMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlSensorMessage_h
