// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StartPolyDataMessage` (type_id: STT_POLYDATA).
// Header-only (no body content).

#ifndef __igtlStartPolyDataMessage_h
#define __igtlStartPolyDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StartPolyDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StartPolyDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StartPolyDataMessage);

 protected:
    StartPolyDataMessage()  { m_SendMessageType = "STT_POLYDATA"; }
    ~StartPolyDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStartPolyDataMessage_h
