// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::PositionMessage` (type_id: POSITION).

#ifndef __igtlPositionMessage_h
#define __igtlPositionMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT PositionMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::PositionMessage, igtl::MessageBase);
    igtlNewMacro(igtl::PositionMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    PositionMessage()  { m_SendMessageType = "POSITION"; }
    ~PositionMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlPositionMessage_h
