// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::StringMessage` (type_id: STRING).

#ifndef __igtlStringMessage_h
#define __igtlStringMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StringMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StringMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StringMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    StringMessage()  { m_SendMessageType = "STRING"; }
    ~StringMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStringMessage_h
