// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::NDArrayMessage` (type_id: NDARRAY).

#ifndef __igtlNDArrayMessage_h
#define __igtlNDArrayMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT NDArrayMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::NDArrayMessage, igtl::MessageBase);
    igtlNewMacro(igtl::NDArrayMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    NDArrayMessage()  { m_SendMessageType = "NDARRAY"; }
    ~NDArrayMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlNDArrayMessage_h
