// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::CapabilityMessage` (type_id: CAPABILITY).

#ifndef __igtlCapabilityMessage_h
#define __igtlCapabilityMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT CapabilityMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::CapabilityMessage, igtl::MessageBase);
    igtlNewMacro(igtl::CapabilityMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    CapabilityMessage()  { m_SendMessageType = "CAPABILITY"; }
    ~CapabilityMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlCapabilityMessage_h
