// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::RTSCommandMessage` (type_id: RTS_COMMAND).
// Header-only (no body content).

#ifndef __igtlRTSCommandMessage_h
#define __igtlRTSCommandMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT RTSCommandMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::RTSCommandMessage, igtl::MessageBase);
    igtlNewMacro(igtl::RTSCommandMessage);

 protected:
    RTSCommandMessage()  { m_SendMessageType = "RTS_COMMAND"; }
    ~RTSCommandMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlRTSCommandMessage_h
