// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StopQuaternionTrackingDataMessage` (type_id: STP_QTDATA).
// Header-only (no body content).

#ifndef __igtlStopQuaternionTrackingDataMessage_h
#define __igtlStopQuaternionTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StopQuaternionTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StopQuaternionTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StopQuaternionTrackingDataMessage);

 protected:
    StopQuaternionTrackingDataMessage()  { m_SendMessageType = "STP_QTDATA"; }
    ~StopQuaternionTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStopQuaternionTrackingDataMessage_h
