// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StopImageMessage` (type_id: STP_IMAGE).
// Header-only (no body content).

#ifndef __igtlStopImageMessage_h
#define __igtlStopImageMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StopImageMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StopImageMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StopImageMessage);

 protected:
    StopImageMessage()  { m_SendMessageType = "STP_IMAGE"; }
    ~StopImageMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStopImageMessage_h
