// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::TrackingDataMessage` (type_id: TDATA).

#ifndef __igtlTrackingDataMessage_h
#define __igtlTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT TrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::TrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::TrackingDataMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    TrackingDataMessage()  { m_SendMessageType = "TDATA"; }
    ~TrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlTrackingDataMessage_h
