// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetStatusMessage` (type_id: GET_STATUS).
// Header-only (no body content).

#ifndef __igtlGetStatusMessage_h
#define __igtlGetStatusMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetStatusMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetStatusMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetStatusMessage);

 protected:
    GetStatusMessage()  { m_SendMessageType = "GET_STATUS"; }
    ~GetStatusMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetStatusMessage_h
