// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetLabelMetaMessage` (type_id: GET_LBMETA).
// Header-only (no body content).

#ifndef __igtlGetLabelMetaMessage_h
#define __igtlGetLabelMetaMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetLabelMetaMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetLabelMetaMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetLabelMetaMessage);

 protected:
    GetLabelMetaMessage()  { m_SendMessageType = "GET_LBMETA"; }
    ~GetLabelMetaMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetLabelMetaMessage_h
