// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetBindMessage` (type_id: GET_BIND).
// Header-only (no body content).

#ifndef __igtlGetBindMessage_h
#define __igtlGetBindMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetBindMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetBindMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetBindMessage);

 protected:
    GetBindMessage()  { m_SendMessageType = "GET_BIND"; }
    ~GetBindMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetBindMessage_h
