// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetImageMessage` (type_id: GET_IMAGE).
// Header-only (no body content).

#ifndef __igtlGetImageMessage_h
#define __igtlGetImageMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetImageMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetImageMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetImageMessage);

 protected:
    GetImageMessage()  { m_SendMessageType = "GET_IMAGE"; }
    ~GetImageMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetImageMessage_h
