// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::RTSBindMessage` (type_id: RTS_BIND).
// Header-only (no body content).

#ifndef __igtlRTSBindMessage_h
#define __igtlRTSBindMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT RTSBindMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::RTSBindMessage, igtl::MessageBase);
    igtlNewMacro(igtl::RTSBindMessage);

 protected:
    RTSBindMessage()  { m_SendMessageType = "RTS_BIND"; }
    ~RTSBindMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlRTSBindMessage_h
