// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StopTrackingDataMessage` (type_id: STP_TDATA).
// Header-only (no body content).

#ifndef __igtlStopTrackingDataMessage_h
#define __igtlStopTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StopTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StopTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StopTrackingDataMessage);

 protected:
    StopTrackingDataMessage()  { m_SendMessageType = "STP_TDATA"; }
    ~StopTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStopTrackingDataMessage_h
