// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::LabelMetaMessage` (type_id: LBMETA).

#ifndef __igtlLabelMetaMessage_h
#define __igtlLabelMetaMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT LabelMetaMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::LabelMetaMessage, igtl::MessageBase);
    igtlNewMacro(igtl::LabelMetaMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    LabelMetaMessage()  { m_SendMessageType = "LBMETA"; }
    ~LabelMetaMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlLabelMetaMessage_h
