// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StopBindMessage` (type_id: STP_BIND).
// Header-only (no body content).

#ifndef __igtlStopBindMessage_h
#define __igtlStopBindMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StopBindMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StopBindMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StopBindMessage);

 protected:
    StopBindMessage()  { m_SendMessageType = "STP_BIND"; }
    ~StopBindMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStopBindMessage_h
