// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::QuaternionTrackingDataMessage` (type_id: QTDATA).

#ifndef __igtlQuaternionTrackingDataMessage_h
#define __igtlQuaternionTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT QuaternionTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::QuaternionTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::QuaternionTrackingDataMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    QuaternionTrackingDataMessage()  { m_SendMessageType = "QTDATA"; }
    ~QuaternionTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlQuaternionTrackingDataMessage_h
