// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::BindMessage` (type_id: BIND).

#ifndef __igtlBindMessage_h
#define __igtlBindMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT BindMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::BindMessage, igtl::MessageBase);
    igtlNewMacro(igtl::BindMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    BindMessage()  { m_SendMessageType = "BIND"; }
    ~BindMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlBindMessage_h
