// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::CommandMessage` (type_id: COMMAND).

#ifndef __igtlCommandMessage_h
#define __igtlCommandMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT CommandMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::CommandMessage, igtl::MessageBase);
    igtlNewMacro(igtl::CommandMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    CommandMessage()  { m_SendMessageType = "COMMAND"; }
    ~CommandMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlCommandMessage_h
