// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::RTSTrackingDataMessage` (type_id: RTS_TDATA).
// Header-only (no body content).

#ifndef __igtlRTSTrackingDataMessage_h
#define __igtlRTSTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT RTSTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::RTSTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::RTSTrackingDataMessage);

 protected:
    RTSTrackingDataMessage()  { m_SendMessageType = "RTS_TDATA"; }
    ~RTSTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlRTSTrackingDataMessage_h
