// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::QueryMessage` (type_id: QUERY).

#ifndef __igtlQueryMessage_h
#define __igtlQueryMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT QueryMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::QueryMessage, igtl::MessageBase);
    igtlNewMacro(igtl::QueryMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    QueryMessage()  { m_SendMessageType = "QUERY"; }
    ~QueryMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlQueryMessage_h
