// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetColorTableMessage` (type_id: GET_COLORT).
// Header-only (no body content).

#ifndef __igtlGetColorTableMessage_h
#define __igtlGetColorTableMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetColorTableMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetColorTableMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetColorTableMessage);

 protected:
    GetColorTableMessage()  { m_SendMessageType = "GET_COLORT"; }
    ~GetColorTableMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetColorTableMessage_h
