// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetPointMessage` (type_id: GET_POINT).
// Header-only (no body content).

#ifndef __igtlGetPointMessage_h
#define __igtlGetPointMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetPointMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetPointMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetPointMessage);

 protected:
    GetPointMessage()  { m_SendMessageType = "GET_POINT"; }
    ~GetPointMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetPointMessage_h
