// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::RTSQuaternionTrackingDataMessage` (type_id: RTS_QTDATA).
// Header-only (no body content).

#ifndef __igtlRTSQuaternionTrackingDataMessage_h
#define __igtlRTSQuaternionTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT RTSQuaternionTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::RTSQuaternionTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::RTSQuaternionTrackingDataMessage);

 protected:
    RTSQuaternionTrackingDataMessage()  { m_SendMessageType = "RTS_QTDATA"; }
    ~RTSQuaternionTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlRTSQuaternionTrackingDataMessage_h
