// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetImageMetaMessage` (type_id: GET_IMGMETA).
// Header-only (no body content).

#ifndef __igtlGetImageMetaMessage_h
#define __igtlGetImageMetaMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetImageMetaMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetImageMetaMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetImageMetaMessage);

 protected:
    GetImageMetaMessage()  { m_SendMessageType = "GET_IMGMETA"; }
    ~GetImageMetaMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetImageMetaMessage_h
