// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::ImageMetaMessage` (type_id: IMGMETA).

#ifndef __igtlImageMetaMessage_h
#define __igtlImageMetaMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT ImageMetaMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::ImageMetaMessage, igtl::MessageBase);
    igtlNewMacro(igtl::ImageMetaMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    ImageMetaMessage()  { m_SendMessageType = "IMGMETA"; }
    ~ImageMetaMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlImageMetaMessage_h
