// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::StatusMessage` (type_id: STATUS).

#ifndef __igtlStatusMessage_h
#define __igtlStatusMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StatusMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StatusMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StatusMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    StatusMessage()  { m_SendMessageType = "STATUS"; }
    ~StatusMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStatusMessage_h
