// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetTrajectoryMessage` (type_id: GET_TRAJ).
// Header-only (no body content).

#ifndef __igtlGetTrajectoryMessage_h
#define __igtlGetTrajectoryMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetTrajectoryMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetTrajectoryMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetTrajectoryMessage);

 protected:
    GetTrajectoryMessage()  { m_SendMessageType = "GET_TRAJ"; }
    ~GetTrajectoryMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetTrajectoryMessage_h
