// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StartBindMessage` (type_id: STT_BIND).
// Header-only (no body content).

#ifndef __igtlStartBindMessage_h
#define __igtlStartBindMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StartBindMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StartBindMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StartBindMessage);

 protected:
    StartBindMessage()  { m_SendMessageType = "STT_BIND"; }
    ~StartBindMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStartBindMessage_h
