// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::GetPolyDataMessage` (type_id: GET_POLYDATA).
// Header-only (no body content).

#ifndef __igtlGetPolyDataMessage_h
#define __igtlGetPolyDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT GetPolyDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::GetPolyDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::GetPolyDataMessage);

 protected:
    GetPolyDataMessage()  { m_SendMessageType = "GET_POLYDATA"; }
    ~GetPolyDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlGetPolyDataMessage_h
