// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit.
//
// Shim facade for upstream's `igtl::StartQuaternionTrackingDataMessage` (type_id: STT_QTDATA).
// Header-only (no body content).

#ifndef __igtlStartQuaternionTrackingDataMessage_h
#define __igtlStartQuaternionTrackingDataMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT StartQuaternionTrackingDataMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::StartQuaternionTrackingDataMessage, igtl::MessageBase);
    igtlNewMacro(igtl::StartQuaternionTrackingDataMessage);

 protected:
    StartQuaternionTrackingDataMessage()  { m_SendMessageType = "STT_QTDATA"; }
    ~StartQuaternionTrackingDataMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlStartQuaternionTrackingDataMessage_h
