// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::ImageMessage` (type_id: IMAGE).

#ifndef __igtlImageMessage_h
#define __igtlImageMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT ImageMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::ImageMessage, igtl::MessageBase);
    igtlNewMacro(igtl::ImageMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    ImageMessage()  { m_SendMessageType = "IMAGE"; }
    ~ImageMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlImageMessage_h
