// GENERATED by corpus-tools/oigtl-corpus codegen cpp-compat — do not edit
// header. Pack/unpack behaviour is STUBBED: this class exists for
// API completeness but carries no typed accessors. To implement,
// replace with a hand-written pair in core-cpp/compat/include/igtl/
// and core-cpp/compat/src/ (see igtlTransformMessage.{h,cxx} for
// the pattern).
//
// Shim facade for upstream's `igtl::ColorTableMessage` (type_id: COLORT).

#ifndef __igtlColorTableMessage_h
#define __igtlColorTableMessage_h

#include "igtlMacro.h"
#include "igtlMessageBase.h"

namespace igtl {

class IGTLCommon_EXPORT ColorTableMessage : public MessageBase {
 public:
    igtlTypeMacro(igtl::ColorTableMessage, igtl::MessageBase);
    igtlNewMacro(igtl::ColorTableMessage);

    // No typed accessors — hand-written replacement required for
    // byte-exact parity with upstream.

 protected:
    ColorTableMessage()  { m_SendMessageType = "COLORT"; }
    ~ColorTableMessage() override = default;
};

}  // namespace igtl

#endif  // __igtlColorTableMessage_h
