"""Pydantic models that are the source of truth for message-schema shape.

These models describe what a file under ``spec/schemas/`` may contain.
Every tool in corpus-tools that reads a schema parses it through
:class:`MessageSchema`; the JSON Schema in ``spec/meta-schema.json`` is
generated from these models rather than hand-authored (see
``oigt_corpus_tools.schema.emit``).

Cross-field rules that are awkward to express in JSON Schema live here
as ``@model_validator(mode="after")`` methods:

- ``trailing_string`` fields must be the last field in a message.
- ``length_prefixed_string`` fields must declare ``length_prefix_type``.
- ``fixed_string`` fields must declare ``size_bytes``.

Additional rules can be added without touching the JSON Schema artifact;
it is regenerated by ``oigt-corpus schema emit-meta``.
"""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    NonNegativeInt,
    StringConstraints,
    model_validator,
)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class ProtocolVersion(str, Enum):
    """OpenIGTLink protocol version in which a feature first appeared."""

    V1 = "v1"
    V2 = "v2"
    V3 = "v3"
    V4 = "v4"


class PrimitiveType(str, Enum):
    """Fixed-width numeric types that can appear directly in a message body."""

    UINT8 = "uint8"
    UINT16 = "uint16"
    UINT32 = "uint32"
    UINT64 = "uint64"
    INT8 = "int8"
    INT16 = "int16"
    INT32 = "int32"
    INT64 = "int64"
    FLOAT32 = "float32"
    FLOAT64 = "float64"


class FieldType(str, Enum):
    """Composite field types — everything that isn't a numeric primitive.

    ``trailing_string`` consumes all remaining body bytes and MUST be the
    last field in its message. ``length_prefixed_string`` requires a
    ``length_prefix_type``. ``fixed_string`` requires ``size_bytes``.
    """

    FIXED_STRING = "fixed_string"
    LENGTH_PREFIXED_STRING = "length_prefixed_string"
    TRAILING_STRING = "trailing_string"
    FIXED_BYTES = "fixed_bytes"
    ARRAY = "array"
    STRUCT_ARRAY = "struct_array"


class Endianness(str, Enum):
    """Byte order for a multi-byte field on the wire."""

    BIG = "big"
    LITTLE = "little"


class Encoding(str, Enum):
    """Text encoding for string-typed fields."""

    ASCII = "ascii"
    UTF_8 = "utf-8"
    BINARY = "binary"


class CountSource(str, Enum):
    """How an array's element count is derived when not given explicitly.

    ``remaining`` means the count is computed at parse time as the number
    of elements that fit in the body bytes not consumed by earlier
    fields: ``count = (body_size - bytes_consumed_so_far) / element_size``.
    The division must be exact — a message whose body_size does not divide
    evenly is malformed. This matches the dominant pattern across the
    OpenIGTLink message catalog (CAPABILITY, POINT, TDATA, QTDATA,
    TRAJECTORY, IMGMETA, LBMETA), where the element count is implicit in
    the body size rather than carried in a header field.

    This enum is reserved for future growth (e.g. an NDARRAY-style
    product-of-sizes variant); today it has a single value.
    """

    REMAINING = "remaining"


# ---------------------------------------------------------------------------
# Shared constrained aliases
# ---------------------------------------------------------------------------


# Identifier matching the snake_case convention used for field names.
LowerIdentifier = Annotated[
    str,
    StringConstraints(pattern=r"^[a-z][a-z0-9_]*$"),
]

# Identifier matching the convention used for message type / struct names.
UpperIdentifier = Annotated[
    str,
    StringConstraints(pattern=r"^[A-Z][A-Z0-9_]*$"),
]

# Wire type identifier — ASCII, up to 12 bytes, all upper/digit/underscore.
TypeIdString = Annotated[
    str,
    StringConstraints(min_length=1, max_length=12, pattern=r"^[A-Z0-9_]+$"),
]

# Size or body_size: non-negative integer or the literal "variable".
Size = Union[NonNegativeInt, Literal["variable"]]

# Array length: either an inline integer count or a sibling-field name.
CountValue = Union[NonNegativeInt, LowerIdentifier]


# Byte sizes of each primitive type. Used to statically derive element
# size for ``count_from: remaining`` validation.
_PRIMITIVE_BYTE_SIZES: dict[PrimitiveType, int] = {
    PrimitiveType.UINT8: 1,
    PrimitiveType.UINT16: 2,
    PrimitiveType.UINT32: 4,
    PrimitiveType.UINT64: 8,
    PrimitiveType.INT8: 1,
    PrimitiveType.INT16: 2,
    PrimitiveType.INT32: 4,
    PrimitiveType.INT64: 8,
    PrimitiveType.FLOAT32: 4,
    PrimitiveType.FLOAT64: 8,
}


# ---------------------------------------------------------------------------
# Spec reference
# ---------------------------------------------------------------------------


class SpecReference(BaseModel):
    """Back-reference from a schema or field into the prose spec document."""

    model_config = ConfigDict(extra="forbid")

    section: str = Field(
        description=(
            "Section identifier in the prose spec document (e.g. '4.3.2' "
            "or 'Body (STATUS)')."
        ),
    )
    document: Optional[str] = Field(
        default=None,
        description=(
            "Prose spec document this entry references "
            "(e.g. 'protocol/v3.md'). Defaults to the document matching "
            "``introduced_in``."
        ),
    )
    url: Optional[str] = Field(
        default=None,
        description="Optional canonical URL for the spec section.",
        json_schema_extra={"format": "uri"},
    )


# ---------------------------------------------------------------------------
# Element descriptor
# ---------------------------------------------------------------------------


class ElementDescriptor(BaseModel):
    """Inline description of an array's element type.

    Used when an array / struct_array field has elements that are more
    complex than a single primitive but simpler than a full referenced
    struct — for example, CAPABILITY's array of 12-byte null-padded
    ASCII strings, where each element is a ``fixed_string`` with
    ``size_bytes: 12``.

    An ElementDescriptor carries only the *wire-shape* attributes
    (``type``, ``size_bytes``, ``encoding``, etc.) — not field-level
    attributes like ``name`` or top-level attributes like ``count``,
    since it describes what a single element looks like, not a field in
    its own right. Descriptions and notes are optional: an element is
    typically documented at its parent field's description.
    """

    model_config = ConfigDict(extra="forbid")

    type: Union[PrimitiveType, FieldType] = Field(
        description=(
            "Wire type of the element. Primitives are the common case; "
            "``fixed_string`` / ``fixed_bytes`` let an array carry "
            "uniformly-sized structured elements."
        ),
    )
    size_bytes: Optional[Size] = Field(
        default=None,
        description=(
            "Element byte size. Required when ``type`` is "
            "``fixed_string`` or ``fixed_bytes``."
        ),
    )
    encoding: Optional[Encoding] = Field(
        default=None,
        description="For string-typed elements: the expected text encoding.",
    )
    endianness: Optional[Endianness] = Field(
        default=None,
        description=(
            "Byte order. Defaults to big-endian (OpenIGTLink convention)."
        ),
    )
    null_padded: Optional[bool] = Field(
        default=None,
        description=(
            "For ``fixed_string`` elements: whether values shorter than "
            "``size_bytes`` are null-padded. Defaults to true."
        ),
    )
    length_prefix_type: Optional[PrimitiveType] = Field(
        default=None,
        description=(
            "For ``length_prefixed_string`` elements: the integer type "
            "of the length prefix."
        ),
    )
    description: Optional[str] = Field(
        default=None,
        description=(
            "Optional. Elements are normally documented via the parent "
            "field's description; use this only when per-element docs "
            "would add clarity."
        ),
    )

    @model_validator(mode="after")
    def _check_type_requirements(self) -> ElementDescriptor:
        if self.type == FieldType.FIXED_STRING and self.size_bytes is None:
            raise ValueError(
                "element of type fixed_string requires size_bytes"
            )
        if self.type == FieldType.FIXED_BYTES and self.size_bytes is None:
            raise ValueError(
                "element of type fixed_bytes requires size_bytes"
            )
        if (
            self.type == FieldType.LENGTH_PREFIXED_STRING
            and self.length_prefix_type is None
        ):
            raise ValueError(
                "element of type length_prefixed_string requires "
                "length_prefix_type"
            )
        if self.type == FieldType.TRAILING_STRING:
            raise ValueError(
                "trailing_string cannot be an array element; it must be a "
                "top-level field and must be the last one in its message"
            )
        return self


# Array element type: a primitive, an inline descriptor, or the name of
# a struct type (struct references are not yet supported by codegen).
ElementType = Union[PrimitiveType, ElementDescriptor, UpperIdentifier]


def _try_element_byte_size(element_type: Any) -> Optional[int]:
    """Return the element's statically-known byte size, or ``None``.

    ``None`` means the size cannot be derived without reading the data
    (e.g. the element is a struct reference whose layout is defined
    elsewhere, or a variable-length element type). Callers that need
    a known size to validate — notably ``count_from: remaining`` — use
    this helper and reject when ``None``.
    """
    if isinstance(element_type, PrimitiveType):
        return _PRIMITIVE_BYTE_SIZES[element_type]
    if isinstance(element_type, ElementDescriptor):
        # Primitive element via descriptor: look up size by type.
        if isinstance(element_type.type, PrimitiveType):
            return _PRIMITIVE_BYTE_SIZES[element_type.type]
        # Fixed-size composite element: size_bytes carries it (and the
        # ElementDescriptor validator has already guaranteed non-None
        # when `type` is fixed_string / fixed_bytes).
        if (
            element_type.type in (FieldType.FIXED_STRING, FieldType.FIXED_BYTES)
            and isinstance(element_type.size_bytes, int)
        ):
            return element_type.size_bytes
        return None
    # UpperIdentifier (named struct) — layout lives elsewhere, not yet
    # resolvable at schema-validation time.
    return None


# ---------------------------------------------------------------------------
# Field
# ---------------------------------------------------------------------------


class FieldSchema(BaseModel):
    """One field in a message body."""

    model_config = ConfigDict(extra="forbid")

    name: LowerIdentifier = Field(
        description=(
            "Field name, snake_case. Used as-is in codegen; language ports "
            "may apply idiomatic casing conversions."
        ),
    )
    type: Union[PrimitiveType, FieldType] = Field(
        description=(
            "Field type. Primitives are encoded in the order declared. "
            "Composite types require additional attributes "
            "(``size_bytes``, ``count``, ``element_type``, "
            "``length_prefix_type``, ``encoding``, etc.). "
            "``trailing_string`` consumes all remaining body bytes and "
            "MUST be the last field in its message."
        ),
    )
    description: str = Field(
        min_length=1,
        description="Concise description of the field's meaning. Required.",
    )
    rationale: Optional[str] = Field(
        default=None,
        description="Optional. Why this field is shaped this way.",
    )
    introduced_in: Optional[ProtocolVersion] = Field(
        default=None,
        description=(
            "Protocol version in which this field first appeared, if "
            "different from the message's ``introduced_in``."
        ),
    )
    endianness: Optional[Endianness] = Field(
        default=None,
        description=(
            "Byte order. Defaults to big-endian (OpenIGTLink convention). "
            "Rarely overridden; if overridden, explain in ``rationale``."
        ),
    )
    size_bytes: Optional[Size] = Field(
        default=None,
        description=(
            "Size in bytes on the wire. Required for ``fixed_string`` and "
            "``fixed_bytes``; optional for other types if derivable from "
            "``type`` alone."
        ),
    )
    count: Optional[CountValue] = Field(
        default=None,
        description=(
            "For ``array`` / ``struct_array``: either a fixed integer "
            "count, or the name of a sibling field that carries the count. "
            "Mutually exclusive with ``count_from``."
        ),
    )
    count_from: Optional[CountSource] = Field(
        default=None,
        description=(
            "For ``array`` / ``struct_array``: derive the element count "
            "implicitly rather than from a fixed integer or sibling field. "
            "Value ``remaining`` means ``count = (body_size - "
            "bytes_consumed_so_far) / element_size``, and the division "
            "must be exact. Mutually exclusive with ``count``; exactly one "
            "of the two is required on array / struct_array fields."
        ),
    )
    element_type: Optional[ElementType] = Field(
        default=None,
        description=(
            "For ``array``: the element's primitive type. For "
            "``struct_array``: the name of an inline struct (not yet "
            "supported)."
        ),
    )
    layout: Optional[str] = Field(
        default=None,
        description=(
            "Optional semantic-layout hint (e.g. 'column_major_3x4' for "
            "TRANSFORM's matrix). Codegen may use this for helper methods; "
            "it has no effect on wire encoding."
        ),
    )
    length_prefix_type: Optional[PrimitiveType] = Field(
        default=None,
        description=(
            "For ``length_prefixed_string``: the integer type used to "
            "encode the length prefix."
        ),
    )
    encoding: Optional[Encoding] = Field(
        default=None,
        description="For string types: the expected text encoding.",
    )
    null_padded: Optional[bool] = Field(
        default=None,
        description=(
            "For ``fixed_string``: whether values shorter than "
            "``size_bytes`` are padded with null bytes (true) or the full "
            "region is treated as the string (false). Defaults to true."
        ),
    )
    null_terminated: Optional[bool] = Field(
        default=None,
        description=(
            "For ``trailing_string``: whether the final byte on the wire "
            "MUST be 0x00. When true, the null is part of the field bytes "
            "(a non-empty string occupies ``len+1`` bytes) and the string "
            "value is the bytes excluding the final null. Defaults to "
            "false."
        ),
    )
    legacy_notes: Optional[list[str]] = Field(
        default=None,
        description=(
            "Historical quirks for this field that must be preserved for "
            "wire compatibility."
        ),
    )
    notes: Optional[list[str]] = Field(
        default=None,
        description=(
            "Other prose notes that do not fit ``rationale`` or "
            "``legacy_notes``."
        ),
    )

    @model_validator(mode="after")
    def _check_type_requirements(self) -> FieldSchema:
        if self.type == FieldType.FIXED_STRING and self.size_bytes is None:
            raise ValueError(
                f"field '{self.name}' of type fixed_string requires "
                f"size_bytes"
            )
        if (
            self.type == FieldType.LENGTH_PREFIXED_STRING
            and self.length_prefix_type is None
        ):
            raise ValueError(
                f"field '{self.name}' of type length_prefixed_string "
                f"requires length_prefix_type"
            )
        if self.type in (FieldType.ARRAY, FieldType.STRUCT_ARRAY):
            has_count = self.count is not None
            has_count_from = self.count_from is not None
            if has_count and has_count_from:
                raise ValueError(
                    f"field '{self.name}' of type {self.type.value} "
                    f"has both `count` and `count_from` set; exactly "
                    f"one is required"
                )
            if not has_count and not has_count_from:
                raise ValueError(
                    f"field '{self.name}' of type {self.type.value} "
                    f"requires one of `count` or `count_from`"
                )
            # count_from=remaining derives the element count from
            # body_size / element_size, so the element size must be
            # statically known at schema-validation time.
            if self.count_from == CountSource.REMAINING:
                if self.element_type is None:
                    raise ValueError(
                        f"field '{self.name}' with count_from=remaining "
                        f"requires element_type"
                    )
                if _try_element_byte_size(self.element_type) is None:
                    raise ValueError(
                        f"field '{self.name}' with count_from=remaining "
                        f"requires an element with a statically-known "
                        f"byte size (a primitive type, or an inline "
                        f"descriptor with size_bytes for fixed_string / "
                        f"fixed_bytes). Struct references by name are "
                        f"not yet resolvable at schema-validation time."
                    )
        return self


# ---------------------------------------------------------------------------
# Extended header (v3)
# ---------------------------------------------------------------------------


class ExtendedHeader(BaseModel):
    """V3 extended-header layout, if non-default for a message type."""

    model_config = ConfigDict(extra="forbid")

    required: Optional[bool] = Field(
        default=None,
        description=(
            "Whether the v3 extended header is required for this message "
            "type."
        ),
    )
    fields: Optional[list[FieldSchema]] = Field(
        default=None,
        description="Extended-header field layout, if non-default.",
    )


# ---------------------------------------------------------------------------
# Message
# ---------------------------------------------------------------------------


class MessageSchema(BaseModel):
    """Top-level schema describing one OpenIGTLink message type."""

    model_config = ConfigDict(extra="forbid")

    message_type: UpperIdentifier = Field(
        description=(
            "Canonical logical name for this message type (e.g. "
            "'TRANSFORM'). Used to construct language-native type names "
            "during codegen."
        ),
    )
    type_id: TypeIdString = Field(
        description=(
            "Wire type identifier. Written as a 12-byte ASCII field, "
            "null-padded on the right. The string value here contains the "
            "significant bytes only; padding is applied during encoding."
        ),
    )
    introduced_in: ProtocolVersion = Field(
        description=(
            "Protocol version in which this message type was first "
            "defined."
        ),
    )
    deprecated_in: Optional[Literal["v2", "v3", "v4"]] = Field(
        default=None,
        description=(
            "Protocol version in which this message type was deprecated, "
            "if any. Deprecated types must still round-trip correctly for "
            "wire compatibility."
        ),
    )
    description: str = Field(
        min_length=1,
        description=(
            "Concise human-readable summary. Required. Flows into every "
            "language port's generated API documentation."
        ),
    )
    rationale: Optional[str] = Field(
        default=None,
        description=(
            "Optional prose explaining why the message type or its wire "
            "layout is shaped this way. Historical or design-decision "
            "context, not behavioral contract."
        ),
    )
    spec_reference: Optional[SpecReference] = Field(
        default=None,
        description="Back-reference into the prose spec document.",
    )
    body_size: Size = Field(
        description=(
            "Total body size in bytes if fixed, or the string 'variable' "
            "if determined by the fields at encode time."
        ),
    )
    fields: list[FieldSchema] = Field(
        description=(
            "Ordered list of fields in the message body. Fields are "
            "parsed in order."
        ),
    )
    extended_header: Optional[ExtendedHeader] = Field(
        default=None,
        description=(
            "V3 extended-header layout for this message type, if "
            "non-default."
        ),
    )
    metadata_allowed: Optional[bool] = Field(
        default=None,
        description=(
            "Whether this message type accepts a trailing metadata block "
            "in v2/v3. Defaults to true."
        ),
    )
    legacy_notes: Optional[list[str]] = Field(
        default=None,
        description=(
            "Historical quirks that must be preserved for wire "
            "compatibility. These are contract, not documentation — every "
            "entry represents a decision that a new implementation must "
            "match. Prefix with a version tag where relevant "
            "(e.g. 'v2.1:')."
        ),
    )
    notes: Optional[list[str]] = Field(
        default=None,
        description=(
            "Other prose notes that do not fit rationale, spec_reference, "
            "or legacy_notes."
        ),
    )
    see_also: Optional[list[UpperIdentifier]] = Field(
        default=None,
        description="Logical names of related message types.",
    )

    @model_validator(mode="after")
    def _check_trailing_string_is_last(self) -> MessageSchema:
        for i, f in enumerate(self.fields):
            if f.type == FieldType.TRAILING_STRING and i != len(self.fields) - 1:
                raise ValueError(
                    f"trailing_string field '{f.name}' must be the last "
                    f"field in the message (found at index {i}, with "
                    f"{len(self.fields) - i - 1} field(s) following)"
                )
        return self
